### ISSUE TITLE
How many heating cycles does the PCB survive?

### ISSUE THREAD

**Issue by manuel-rw** [DerSpatz/PCB-reflow-solder-heat-plate#12]
Hello everyone,
I want to get into SMD soldering.
Can anyone tell me, how many cycles / thermal stress this PCB usually survives, until it deteriorates?
I know that many factors will influence this, but it would be useful to get a general idea what to expect.

Thank you!
Best regards

**Comment by bwack** [comment]
Learning SMD soldering is fun !
With the current solution, and its huge temperature swings, the longevity is pretty poor.
If you can modify the board with an NTC thermistor (see the other issuehere), you can get more life out of it. Then you can get better control of the temps. I experimented with an IR Thermal sensor. It worked too.

**Comment by manuel-rw** [comment]
Hi, thanks for the reply.
Since the heating PCB is not replaceable, what endurance are you getting with the IR?
It shocked me seeing people mentioning only 5 cycles, but I'm not sure how accurate that is.

**Comment by bwack** [comment]
I think the 5 cycles is due to the huge temperature swings causing it to overheat. 

I haven't used mine more than maybe 10 times, but the pcb is still holding up. no warping.

**Comment by bwack** [comment]
Here is a video of my experimentation with IR sensor.
https://www.youtube.com/watch?v=z8zI6PzrAY8

**Comment by manuel-rw** [comment]
Thanks @bwack for answering.
I think I will stick with my hot air gun for now.
Closing this issue since it's resolved :)
